# Copyright (C)  2018, 2019 Heiko Stamer <HeikoStamer@gmx.net>
#
# Permission is granted to copy, distribute and/or modify this document under
# the terms of the GNU Free Documentation License, Version 1.3 or any later
# version published by the Free Software Foundation; with no Invariant Sections,
# no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is
# included in the sources of this package and additionally can be obtained from
# the Internet <https://www.gnu.org/licenses>.
#
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgcrypt20-dev
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool
  - sudo apt-get install -y texinfo
language: cpp
compiler:
  - clang
  - gcc
script: autoreconf -v -i -f && ./configure && make

