.TH DKG\-DECRYPT "1" "March 2017" "LibTMCG 1.3.0" "User Commands"

.SH NAME
dkg\-decrypt \- distributed decryption for OpenPGP

.SH SYNOPSIS
.B dkg\-decrypt
.RI [ options ]
.IR PEERS

.SH DESCRIPTION
This program decrypts a given message in armored OpenPGP format, where the private key
(only ElGamal) is shared between multiple parties with dkg\-generate(1). For decryption
at least t+1 decryption shares are needed. Currently, only AES\-256 is supported as
symmetric algorithm.
.br
There are two modes of operation: First, the interactive mode using GNUnet for exchange of
the decryption shares, where PEERS must be the same list of GNUnet peer identities used
at the corresponding initial call of dkg\-generate(1). Second, in the non\-interactive mode
the parameter PEERS contains only the GNUnet identity of this peer. Then the own decryption
share is printed, and the user must exchange the shares manually before decryption starts.

.SH OPTIONS
Arguments mandatory for long options are also mandatory for short options.
.TP
\fB\-c\fR, \fB\-\-config\fR=\fI\,FILENAME\/\fR
use GNUnet configuration file FILENAME
.TP
\fB\-h\fR, \fB\-\-help\fR
print this help
.TP
\fB\-L\fR, \fB\-\-log\fR=\fI\,LOGLEVEL\/\fR
configure logging to use LOGLEVEL
.TP
\fB\-l\fR, \fB\-\-logfile\fR=\fI\,FILENAME\/\fR
configure logging to write logs to FILENAME
.TP
\fB\-n\fR, \fB\-\-non\-interactive\fR
run in non\-interactive mode
.TP
\fB\-p\fR, \fB\-\-port\fR
GNUnet CADET port to listen/connect
.TP
\fB\-v\fR, \fB\-\-version\fR
print the GNUnet version number
.TP
\fB\-w\fR, \fB\-\-wait\fR
minutes to wait until start of decryption (only interactive mode)

.SH "REPORTING BUGS"
Report bugs via <http://savannah.nongnu.org/bugs/?group=libtmcg>
.br
Home page of LibTMCG: <http://www.nongnu.org/libtmcg/>

.SH "SEE ALSO"
dkg\-generate(1), dkg\-encrypt(1)

