.TH DKG\-DECRYPT "1" "March 2017" "LibTMCG 1.3.0" "User Commands"

.SH NAME
dkg\-decrypt \- threshold decryption for OpenPGP

.SH SYNOPSIS
.B dkg\-decrypt
.RI [ options ]
.IR PEERS

.SH DESCRIPTION
This program decrypts a message given in armored OpenPGP format, where the
private key has been shared between multiple parties by
.BR dkg\-generate (1).
For successful decryption at least t+1 decryption shares from different 
participants are needed. The threshold parameter t was fixed during key 
generation and cannot changed at this stage of processing.
.PP
Currently, only ElGamal and AES\-256 are supported as cryptographic algorithms.
.PP
There are two modes of operation: First, the interactive mode employs GNUnet
for exchange of the decryption shares, where PEERS must be the same list of
GNUnet peer identities used during key generation with
.BR dkg\-generate (1).
Second, in the non\-interactive mode the parameter PEERS contains only the
GNUnet identity of this peer. Then the corresponding decryption share is
written to STDOUT, and the user must exchange the shares manually before
decryption can start.

.SH OPTIONS
Arguments mandatory for long options are also mandatory for short options.
.TP
\fB\-c\fR, \fB\-\-config\fR=\fI\,FILENAME\/\fR
use GNUnet configuration file FILENAME (only interactive mode)
.TP
\fB\-h\fR, \fB\-\-help\fR
print this help
.TP
\fB\-L\fR, \fB\-\-log\fR=\fI\,LOGLEVEL\/\fR
configure logging to use LOGLEVEL
.TP
\fB\-l\fR, \fB\-\-logfile\fR=\fI\,FILENAME\/\fR
configure logging to write logs to FILENAME
.TP
\fB\-n\fR, \fB\-\-non\-interactive\fR
switch to non\-interactive mode
.TP
\fB\-p\fR, \fB\-\-port\fR
GNUnet CADET port to listen/connect (only interactive mode)
.TP
\fB\-v\fR, \fB\-\-version\fR
print the GNUnet version number
.TP
\fB\-V\fR, \fB\-\-verbose\fR
turn on verbose output (only interactive mode)
.TP
\fB\-w\fR, \fB\-\-wait\fR
minutes to wait until start of share exchange (only interactive mode)

.SH "SECURITY"
The current implementation is in experimental state and should NOT
be used in production environments.

.SH "REPORTING BUGS"
Security vulnerabilities or cryptographic complaints should be reported
via an email directly to
<HeikoStamer@gmx.net>.
Reported problems will be published after they've been fixed.
.PP
Please report other bugs via <http://savannah.nongnu.org/bugs/?group=libtmcg>
.PP
Home page of LibTMCG: <http://www.nongnu.org/libtmcg/>

.SH "EXAMPLES"
TODO

.SH "SEE ALSO"
.BR dkg\-generate (1),
.BR dkg\-encrypt (1)

